### ISSUE TITLE
Enable Kiali to create and manipulate iter8 experiments

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/kiali#1]
Kiali backend component that communicates with Istio parts, retrieves and processes data, and exposes this data to the front-end. For iter8 integration, it makes use of Kiali extension which handle all the needed business logics.

- [ ]  Validate Iter8 CRD, verify Iter8 controller and analytic services. including versioning control #4
- [ ]  Provided API endpoints for Kiali UI - get, create, update, delete. #5
- [ ]  Additional control endpoints - Pause, Rollforward, Rollback #6 
- [ ]  Metrics endpoints - Kiali default metrics and Iter8 Metrics. #7
